server.port=8000
spring.application.name=SpringSecurity
spring.datasource.url=jdbc:postgresql://localhost:5432/security_bank
spring.datasource.username=daniel
spring.datasource.password=importare
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5